// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: tweets.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTweet = `-- name: CreateTweet :one
INSERT INTO tweets (id, created_at, updated_at, content, user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, content, user_id
`

type CreateTweetParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Content   string
	UserID    uuid.UUID
}

func (q *Queries) CreateTweet(ctx context.Context, arg CreateTweetParams) (Tweet, error) {
	row := q.db.QueryRowContext(ctx, createTweet,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Content,
		arg.UserID,
	)
	var i Tweet
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Content,
		&i.UserID,
	)
	return i, err
}
